<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */
//* Template Name: Blog

global $bp;                
$current_language = "eng";
$current_language_slug = "";
if( defined('ICL_LANGUAGE_CODE') )
{
    $current_language = cur_get_current_language(ICL_LANGUAGE_CODE); 
    $current_language_slug = ( ICL_LANGUAGE_CODE == "en" ? "":"/".ICL_LANGUAGE_CODE );
}
//======= If user on /blog page then sort by post modified date.
if($current_language!='eng' && is_array($bp->unfiltered_uri) && count($bp->unfiltered_uri) === 1 && $bp->unfiltered_uri[0] === 'blog' )
{     
    remove_action('genesis_loop', 'genesis_do_loop');
    add_action( 'genesis_loop', 'curr_content_loop' );    
}
function curr_content_loop()
{
    global $paged; // current paginated page
    global $query_args; // grab the current wp_query() args
    
    $args = array(
        'orderby' => 'modified',         
        'paged'   => $paged,
    );
    genesis_custom_loop( wp_parse_args($query_args, $args) );
}

//* The blog page loop logic is located in lib/structure/loops.php
add_filter('genesis_pre_get_option_site_layout', '__genesis_return_full_width_content');
add_action( 'genesis_before_loop', 'genesis_do_search_title' );
/**
 * Echo the title with the search term.
 *
 * @since 1.9.0
 */
function genesis_do_search_title() {

	$title = sprintf( '<div class="archive-description"><h1 class="archive-title">%s %s</h1></div>', apply_filters( 'genesis_search_title_text', __( '', 'genesis' ) ), curriki_getSearchBar() );

	echo apply_filters( 'genesis_search_title_output', $title ) . "\n";

}
function curriki_getSearchBar(){
    //return
    '<form method="get" action="">Search Results for: <input type="search" placeholder="Search Blog Posts" name="s" value="'.get_search_query().'" class="blog_search"><input type="submit" value="" class="blog_search_button"></form>';
}
genesis();
